root: true
parserOptions:
  parser: '@babel/eslint-parser'
env:
  es6: true
  node: true
rules:
  'import/prefer-default-export': 0
  'import/no-extraneous-dependencies': 0
extends:
  - 'eslint:recommended'
  - 'plugin:import/recommended'
  - 'plugin:import/typescript'
  - 'plugin:astro/recommended'