root: true
env:
  es6: true
  node: true
rules:
  'react/jsx-uses-react': 'error'
  'react/jsx-uses-vars': 'error'
parserOptions:
  sourceType: 'module'
  ecmaVersion: 2021
extends:
  - 'eslint:recommended'
  - 'plugin:react/jsx-runtime'
  - 'plugin:astro/recommended'
