extends:
  - 'stylelint-config-standard'
  - 'stylelint-config-recess-order'
  - 'stylelint-config-standard-scss'
  - 'stylelint-config-astro'
ignoreFiles:
  - '**/*.js'
  - '**/*.ts'
  - '**/*.jsx'
  - '**/*.mjs'
  - '**/*.yml'
  - '**/*.yaml'
  - '.storybook/**/*'
