extends:
  - 'stylelint-config-standard'
  - 'stylelint-config-recess-order'
  - 'stylelint-config-standard-scss'
  - 'stylelint-config-astro'
  - 'stylelint-config-recommended-vue'
  - 'stylelint-config-recommended-vue/scss'
